### ISSUE TITLE
Thx for making this base64 method!

### ISSUE THREAD

**Issue by LintaoAmons** [HakonHarnes/img-clip.nvim#10]
I have been waiting for this kind of thing for a long time. Didn't find more time to spike and learn to do it myself.

I shall learn from you implementation and try to add this functionality to obsidian

**Comment by HakonHarnes** [comment]
> I have been waiting for this kind of thing for a long time. Didn't find more time to spike and learn to do it myself.
> 
> I shall learn from you implementation and try to add this functionality to obsidian

Thank you and good luck with your own plugin!
