### ISSUE TITLE
Suggestion: Elegantly disable plugin when running without an x session

### ISSUE THREAD

**Issue by jarbus** [HakonHarnes/img-clip.nvim#49]
**Is your feature request related to a problem? Please describe.**
Love this plugin and added it to my dotfiles. I get a popup whenever I open neovim over SSH that says `Could not get clipboard command. See :checkhealth img-clip`. I have xclip installed, but this error pops up over SSH because xclip doesn't find an X session. When I connect with ssh -X everything works fine.

**Describe the solution you'd like**
I propose some way of detecting when an X session is not found, and disabling the pop-up message.

**Comment by jarbus** [comment]
It does indeed! Thanks for the quick fix!

**Comment by HakonHarnes** [comment]
No problem! Glad you like the plugin :)
