### ISSUE TITLE
Plugin Fails in a Non-POSIX Compatible Shell

### ISSUE THREAD

**Issue by szsdk** [HakonHarnes/img-clip.nvim#64]
In a non-POSIX compatible shell, the execution of the paste command will fail. My suggestion is to change this line:
https://github.com/HakonHarnes/img-clip.nvim/blob/61ece8b8a206a31459d3f3ff186d6e2b2f958356/lua/img-clip/util.lua#L36
to something like `sh -c $input_cmd`.

**Comment by HakonHarnes** [comment]
Thanks for reporting and the suggestion. Does [fix/non-posix-compliant-shells](https://github.com/HakonHarnes/img-clip.nvim/tree/fix/non-posix-compliant-shells) address the issue for you?

**Comment by szsdk** [comment]
Yes. It addresses my issue. Thanks for your quick response.
