### ISSUE TITLE
Can we use relative file path?

### ISSUE THREAD

**Issue by pacaunt** [HakonHarnes/img-clip.nvim#80]
I've tried this with insert image to my typst document and feel quite amazing about its functionality. However, when inserting images by using drag and drop from nautilus (a file explorer in Ubuntu) to neovim, the file path always become absolute path. For example, the image is in the directory 
```
/home/pacaunt/Documents/ChemicalEquilibrium/lecture/img/02graphdes.png
```
and I dragged the image to 
```
/home/pacaunt/Documents/ChemicalEquilibrium/lecture/ChemicalEquilibrium.typ
```
The given path of the image is in the form 
```typst
#figure(
  image("/home/pacaunt/Documents/ChemicalEquilibrium/lecture/img/02graphdes.png", width: 80%),
  caption: [],
) <fig-02graphdes>

```
which is not allowed in typst (typst cannot access the outer current directory files). The valid path of this is 
```typst
#figure(
  image("./img/02graphdes.png", width: 80%),
  caption: [],
) <fig-02graphdes>
```

I tried setting `relative_to_current_file = true` but that did not work. Is there a new functionality for this?

**Comment by HakonHarnes** [comment]
Thanks for pointing this out. 

Does the [fix/relative-path-drag-and-drop](https://github.com/HakonHarnes/img-clip.nvim/tree/fix/relative-path-drag-and-drop) branch resolve the issue for you? If you're using lazy.nvim, set `branch = "fix/relative-path-drag-and-drop"`.

**Comment by HakonHarnes** [comment]
@pacaunt A fix has been merged into main. It shouldn't require setting `relative_to_current_file` as long as `use_absolute_path` is `false`. So in other words; it should work out of the box now.
