### ISSUE TITLE
ERROR Operating system is not supported

### ISSUE THREAD

**Issue by liyiyuian** [HakonHarnes/img-clip.nvim#84]
**Describe the bug**
I am using Ubuntu 22.04, have `xclip` installed. When I run `checkhealth img-clip`, I got `ERROR Operating system is not supported` .

**Steps to reproduce**
Run `checkhealth img-clip`. 

**Desktop (please complete the following information):**
- OS: Ubuntu 22.04
-  Neovim version: v0.10.0
- Emulator: Kitty 0.32.1

Thank you!

**Comment by HakonHarnes** [comment]
Thanks for reporting.

I suspect your `DISPLAY` environment variable is not set. Are you using ssh by chance? If that's the case you'll need to forward your X11 session with the `-X` flag. What's the output of `echo $DISPLAY` in your terminal?

**Comment by liyiyuian** [comment]
Hi! Thank you for replying! I am running it on a local machine, and the DISPLAY is set to `:0`.

**Comment by HakonHarnes** [comment]
Glad you got it fixed! Thank you for the kind words.
