### ISSUE TITLE
avoid overwriting images

### ISSUE THREAD

**Issue by max397574** [HakonHarnes/img-clip.nvim#86]
**Is your feature request related to a problem? Please describe.**
I use this for my notes and so it can happen that I have a lot of different images from different files together. Now when I get prompted for the filename it can happen that I enter a filename of an already existing file. This then overwrites the existing image and it is lost.

**Describe the solution you'd like**
Detect when the file already exists and do sth like e.g. appending increasing numbers

**Describe alternatives you've considered**
Just live with it or hack together my own solution e.g. by appending a timestamp to the image (if that is possible, haven't checked that out yet)

**Comment by HakonHarnes** [comment]
You can do something like this to always append a timestamp to the filename: 

```lua
opts = {
  default = {
    file_name = function()
      local file_name = vim.fn.input("File name: ")
      local timestamp = os.date("%Y-%m-%d-%H-%M-%S")
      return file_name .. "-" .. timestamp
    end,
    prompt_for_file_name = false,
  },
}
```

Does that help?
